#
# Standard Diplomacy Variant
#
# Map
#
# The Map Dictionary is of the form 
#
#	key : Province Name     value : { Aliases, Borders }
#
#
# Aliases = list of alternative Names for the Province (the first is the default name)
# Borders = adjacent Map spaces listed in CONSECUTIVE CLOCKWISE ORDER (including OTB)
#

OTB = 'OTB'     # Off The Board (an "edge" of the Map)


Map = {	'Adr'	: {	'Aliases' : [ 'Adriatic Sea' ],
				'Borders' : [ 'Ven', 'Tri', 'Alb', 'Ion', 'Apu' ] },
		'Aeg'	: {	'Aliases' : [ 'Aegean Sea' ],
				'Borders' : [ 'Ion', 'Gre', 'Bul', 'Con', 'Smy', 'Eas' ] },
		'Alb'	: {	'Aliases' : [ 'Albania' ],
				'Borders' : [ 'Tri', 'Ser', 'Gre', 'Ion', 'Adr' ] },
		'Ank'	: {	'Aliases' : [ 'Ankara' ],
				'Borders' : [ 'Con', 'Bla', 'Arm', 'Smy' ] },
		'Apu'	: {	'Aliases' : [ 'Apulia' ],
				'Borders' : [ 'Nap', 'Rom', 'Ven', 'Adr', 'Ion' ] },
		'Arm'	: {	'Aliases' : [ 'Armenia' ],
				'Borders' : [ 'Syr', 'Smy', 'Ank', 'Bla', 'Sev', OTB ] },
		'Bal'	: {	'Aliases' : [ 'Baltic Sea' ],
				'Borders' : [ 'Den', 'Swe', 'GoB', 'Lvn', 'Pru', 'Ber', 'Kie' ] },
		'Bar'	: {	'Aliases' : [ 'Barents Sea' ],
				'Borders' : [ 'Nwg', OTB, 'StP', 'Nwy' ] },
		'Bel'	: {	'Aliases' : [ 'Belgium' ],
				'Borders' : [ 'Hol', 'Ruh', 'Bur', 'Pic', 'Eng', 'Nth' ] },
		'Ber'	: {	'Aliases' : [ 'Berlin' ],
				'Borders' : [ 'Pru', 'Sil', 'Mun', 'Kie', 'Bal' ] },
		'Bla'	: {	'Aliases' : [ 'Black Sea' ],
				'Borders' : [ 'Rum', 'Sev', 'Arm', 'Ank', 'Con', 'Bul' ] },
		'Boh'	: {	'Aliases' : [ 'Bohemia' ],
				'Borders' : [ 'Gal', 'Vie', 'Tyr', 'Mun', 'Sil' ] },
		'Bre'	: {	'Aliases' : [ 'Brest' ],
				'Borders' : [ 'Gas', 'Mid' , 'Eng', 'Pic', 'Par' ] },
		'Bud'	: {	'Aliases' : [ 'Budapest' ],
				'Borders' : [ 'Tri', 'Vie', 'Gal', 'Rum', 'Ser' ] },
		'Bul'	: {	'Aliases' : [ 'Bulgaria' ],
				'Borders' : [ 'Con', 'Aeg' , 'Gre', 'Ser', 'Rum', 'Bla'] },
		'Bur'	: {	'Aliases' : [ 'Burgundy' ],
				'Borders' : [ 'Swi', 'Mar', 'Gas', 'Par', 'Pic', 'Bel', 'Ruh', 'Mun' ] },
		'Cly'	: {	'Aliases' : [ 'Clyde' ],
				'Borders' : [ 'Edi', 'Lvp', 'NAt', 'Nwg' ] },
		'Con'	: {	'Aliases' : [ 'Constantinople' ],
				'Borders' : [ 'Ank', 'Smy', 'Aeg', 'Bul', 'Bla' ] },
		'Den'	: {	'Aliases' : [ 'Denmark' ],
				'Borders' : [ 'Kie', 'Hel', 'Nth', 'Ska', 'Swe', 'Bal' ] },
		'Eas'	: {	'Aliases' : [ 'Eastern Mediterranean' ],
				'Borders' : [ 'Ion', 'Aeg', 'Smy', 'Syr', OTB ] },
		'Edi'	: {	'Aliases' : [ 'Edinburgh' ],
				'Borders' : [ 'Lvp', 'Cly', 'Nwg', 'Nth', 'Yor'] },
		'Eng'	: {	'Aliases' : [ 'English Channel' ],
				'Borders' : [ 'Bel', 'Pic', 'Bre', 'Mid', 'Iri', 'Wal', 'Lon', 'Nth' ] },
		'Fin'	: {	'Aliases' : [ 'Finland' ],
				'Borders' : [ 'Nwy', 'StP', 'GoB', 'Swe' ] },
		'Gal'	: {	'Aliases' : [ 'Galicia' ],
				'Borders' : [ 'Bud', 'Vie', 'Boh', 'Sil', 'War', 'Ukr', 'Rum' ] },
		'Gas'	: {	'Aliases' : [ 'Gascony' ],
				'Borders' : [ 'Bre', 'Par', 'Bur', 'Mar', 'Spa', 'Mid' ] },
		'Gre'	: {	'Aliases' : [ 'Greece' ],
				'Borders' : [ 'Alb', 'Ser', 'Bul', 'Aeg', 'Ion' ] },
		'GoB'	: {	'Aliases' : [ 'Gulf of Bothnia', 'Bot' ],
				'Borders' : [ 'Bal', 'Swe' , 'Fin', 'StP', 'Lvn'] },
		'GoL'	: {	'Aliases' : [ 'Gulf of Lyon', 'Lyo' ],
				'Borders' : [ 'Mar', 'Pie', 'Tus', 'TyS', 'Wes' , 'Spa'] },
		'Hel'	: {	'Aliases' : [ 'Helgoland Bight' ],
				'Borders' : [ 'Den', 'Kie', 'Hol', 'Nth' ] },
		'Hol'	: {	'Aliases' : [ 'Holland' ],
				'Borders' : [ 'Bel', 'Nth', 'Hel', 'Kie', 'Ruh'] },
		'Ion'	: {	'Aliases' : [ 'Ionian Sea' ],
				'Borders' : [ 'Adr', 'Alb', 'Gre', 'Aeg', 'Eas', OTB, 'Tun', 'TyS', 'Nap', 'Apu' ] },
		'Iri'	: {	'Aliases' : [ 'Irish Sea' ],
				'Borders' : [ 'Eng', 'Mid', 'NAt', 'Lvp', 'Wal' ] },
		'Kie'	: {	'Aliases' : [ 'Kiel' ],
				'Borders' : [ 'Ber', 'Mun', 'Ruh', 'Hol', 'Hel', 'Den', 'Bal' ] },
		'Lon'	: {	'Aliases' : [ 'London' ],
				'Borders' : [ 'Eng', 'Wal', 'Yor', 'Nth' ] },
		'Lvn'	: {	'Aliases' : [ 'Livonia' ],
				'Borders' : [ 'StP', 'Mos', 'War', 'Pru', 'Bal', 'GoB'] },
		'Lvp'	: {	'Aliases' : [ 'Liverpool' ],
				'Borders' : [ 'Cly', 'Edi', 'Yor', 'Wal', 'Iri', 'NAt' ] },
		'Mar'	: {	'Aliases' : [ 'Marseilles' ],
				'Borders' : [ 'Swi', 'Pie', 'GoL', 'Spa', 'Gas', 'Bur' ] },
		'Mid'	: {	'Aliases' : [ 'Mid-Atlantic Ocean', 'MAO' ],
				'Borders' : [ 'Eng', 'Bre', 'Gas', 'Spa', 'Por', 'Spa', 'Wes', 'NAf', OTB, 'NAt', 'Iri' ] },
		'Mos'	: {	'Aliases' : [ 'Moscow' ],
				'Borders' : [ 'Lvn', 'StP', OTB, 'Sev', 'Ukr', 'War' ] },
		'Mun'	: {	'Aliases' : [ 'Munich' ],
				'Borders' : [ 'Swi', 'Bur', 'Ruh', 'Kie', 'Ber', 'Sil', 'Boh', 'Tyr' ] },
		'NAf'	: {	'Aliases' : [ 'North Africa' ],
				'Borders' : [ 'Mid', 'Wes', 'Tun', OTB ] },
		'Nap'	: {	'Aliases' : [ 'Naples' ],
				'Borders' : [ 'Rom', 'Apu', 'Ion', 'TyS' ] },
		'NAt'	: {	'Aliases' : [ 'North Atlantic Ocean', 'NAO' ],
				'Borders' : [ 'Nwg', 'Cly', 'Lvp', 'Iri', 'Mid', OTB ] },
		'Nwg'	: {	'Aliases' : [ 'Norwegian Sea', 'Nrg' ],
				'Borders' : [ 'Bar', 'Nwy', 'Nth', 'Edi', 'Cly', 'NAt', OTB ] },
		'Nth'	: {	'Aliases' : [ 'North Sea' ],
				'Borders' : [ 'Edi', 'Nwg', 'Nwy', 'Ska', 'Den', 'Hel', 'Hol', 'Bel', 'Eng', 'Lon', 'Yor' ] },
		'Nwy'	: {	'Aliases' : [ 'Norway' ],
				'Borders' : [ 'Nth', 'Nwg', 'Bar', 'StP', 'Fin', 'Swe', 'Ska' ] },
		'Par'	: {	'Aliases' : [ 'Paris' ],
				'Borders' : [ 'Bur', 'Gas', 'Bre', 'Pic' ] },
		'Pic'	: {	'Aliases' : [ 'Picardy' ],
				'Borders' : [ 'Bel', 'Bur', 'Par', 'Bre', 'Eng' ] },
		'Pie'	: {	'Aliases' : [ 'Piedmont' ],
				'Borders' : [ 'Mar', 'Swi', 'Tyr', 'Ven', 'Tus', 'GoL' ] },
		'Por'	: {	'Aliases' : [ 'Portugal' ],
				'Borders' : [ 'Spa', 'Mid' ] },
		'Pru'	: {	'Aliases' : [ 'Prussia' ],
				'Borders' : [ 'Lvn', 'War', 'Sil', 'Ber', 'Bal' ] },
		'Rom'	: {	'Aliases' : [ 'Rome' ],
				'Borders' : [ 'Tus', 'Ven', 'Apu', 'Nap', 'TyS' ] },
		'Ruh'	: {	'Aliases' : [ 'Ruhr' ],
				'Borders' : [ 'Bur', 'Bel', 'Hol', 'Kie', 'Mun' ] },
		'Rum'	: {	'Aliases' : [ 'Rumania' ],
				'Borders' : [ 'Bul', 'Ser', 'Bud', 'Gal', 'Ukr', 'Sev', 'Bla' ] },
		'Ser'	: {	'Aliases' : [ 'Serbia' ],
				'Borders' : [ 'Bud', 'Rum', 'Bul', 'Gre', 'Alb', 'Tri' ] },
		'Sev'	: {	'Aliases' : [ 'Sevastopol' ],
				'Borders' : [ 'Arm', 'Bla', 'Rum', 'Ukr', 'Mos', OTB ] },
		'Sil'	: {	'Aliases' : [ 'Silesia' ],
				'Borders' : [ 'Gal', 'Boh', 'Mun', 'Ber', 'Pru', 'War' ] },
		'Ska'	: {	'Aliases' : [ 'Skagerrak' ],
				'Borders' : [ 'Den', 'Nth', 'Nwy', 'Swe' ] },
		'Smy'	: {	'Aliases' : [ 'Smyrna' ],
				'Borders' : [ 'Aeg', 'Con', 'Ank', 'Arm', 'Syr', 'Eas' ] },
		'Spa'	: {	'Aliases' : [ 'Spain' ],
				'Borders' : [ 'Mid', 'Por', 'Mid', 'Gas', 'Mar', 'GoL', 'Wes' ] },
		'StP'	: {	'Aliases' : [ 'St. Petersburg' ],
				'Borders' : [ 'Mos', 'Lvn', 'GoB', 'Fin', 'Nwy', 'Bar', OTB ] },
		'Swe'	: {	'Aliases' : [ 'Sweden' ],
				'Borders' : [ 'Nwy', 'Fin', 'GoB', 'Bal', 'Den', 'Ska' ] },
		'Swi'	: {	'Aliases' : [ 'Switzerland' ],
				'Borders' : [ 'Pie', 'Mar', 'Bur', 'Mun', 'Tyr' ] },
		'Syr'	: {	'Aliases' : [ 'Syria' ],
				'Borders' : [ 'Eas', 'Smy', 'Arm', OTB ] },
		'Tri'	: {	'Aliases' : [ 'Trieste' ],
				'Borders' : [ 'Ven', 'Tyr', 'Vie', 'Bud', 'Ser', 'Alb', 'Adr' ] },
		'Tun'	: {	'Aliases' : [ 'Tunis' ],
				'Borders' : [ 'NAf', 'Wes', 'TyS', 'Ion', OTB ] },
		'Tus'	: {	'Aliases' : [ 'Tuscany' ],
				'Borders' : [ 'GoL', 'Pie', 'Ven', 'Rom', 'TyS' ] },
		'Tyr'	: {	'Aliases' : [ 'Tyrolia' ],
				'Borders' : [ 'Tri', 'Ven', 'Pie', 'Swi', 'Mun', 'Boh', 'Vie' ] },
		'TyS'	: {	'Aliases' : [ 'Tyrrhenian Sea' ],
				'Borders' : [ 'GoL', 'Tus', 'Rom', 'Nap', 'Ion', 'Tun', 'Wes' ] },
		'Ukr'	: {	'Aliases' : [ 'Ukraine' ],
				'Borders' : [ 'Mos', 'Sev', 'Rum', 'Gal', 'War' ] },
		'Ven'	: {	'Aliases' : [ 'Venice' ],
				'Borders' : [ 'Apu', 'Rom', 'Tus', 'Pie', 'Tyr', 'Tri', 'Adr' ] },
		'Vie'	: {	'Aliases' : [ 'Vienna' ],
				'Borders' : [ 'Boh', 'Gal', 'Bud', 'Tri', 'Tyr' ] },
		'Wal'	: {	'Aliases' : [ 'Wales' ],
				'Borders' : [ 'Lvp', 'Yor', 'Lon', 'Eng', 'Iri' ] },
		'War'	: {	'Aliases' : [ 'Warsaw' ],
				'Borders' : [ 'Gal', 'Sil', 'Pru', 'Lvn', 'Mos', 'Ukr' ] },
		'Wes'	: {	'Aliases' : [ 'Western Mediterranean', 'WMS' ],
				'Borders' : [ 'Tun', 'NAf', 'Mid', 'Spa', 'GoL', 'TyS' ] },
		'Yor'	: {	'Aliases' : [ 'Yorkshire' ],
				'Borders' : [ 'Lon', 'Wal', 'Lvp', 'Edi', 'Nth' ] }
	  }
